Update devsecopsworkflow.yml

diff --git a/.github/workflows/devsecopsworkflow.yml b/.github/workflows/devsecopsworkflow.yml
--- a/.github/workflows/devsecopsworkflow.yml
+++ b/.github/workflows/devsecopsworkflow.yml
@@ -124,40 +124,40 @@ jobs:
     #   with:
     #     script: |
     #       core.setFailed('Overall coverage is less than 80%!')
-  Snyk: 
-      needs: Build_and_test
-      runs-on: ubuntu-latest
-      steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  # Snyk: 
+  #     needs: Build_and_test
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Use Node.js 
-        uses: actions/setup-node@v1
-        with:
-          node-version: 11.x
+  #     - name: Use Node.js 
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: 11.x
    
-      - name: Install Snyk CLI
-        run: npm install -g snyk@1.1237.0 
+  #     - name: Install Snyk CLI
+  #       run: npm install -g snyk@1.1237.0 
 
-      - name: Authenticate Snyk
-        run: snyk auth ${{ secrets.SNYK_KEY }}
+  #     - name: Authenticate Snyk
+  #       run: snyk auth ${{ secrets.SNYK_KEY }}
 
-      - name: Run Snyk Test
-        run: |
-          snyk test --all-projects
-          echo $?      
-        continue-on-error: true
+  #     - name: Run Snyk Test
+  #       run: |
+  #         snyk test --all-projects
+  #         echo $?      
+  #       continue-on-error: true
         
-      - name: snyk status
-        run: |
-          echo $?
-          snyk_exit_status=$?
-          if [ $snyk_exit_status -eq 0 ]; then
-            echo "Snyk test passed, no vulnerabilities found."
-          else
-            echo "Snyk test failed, vulnerabilities found."
-            exit 1
-          fi
+  #     - name: snyk status
+  #       run: |
+  #         echo $?
+  #         snyk_exit_status=$?
+  #         if [ $snyk_exit_status -eq 0 ]; then
+  #           echo "Snyk test passed, no vulnerabilities found."
+  #         else
+  #           echo "Snyk test failed, vulnerabilities found."
+  #           exit 1
+  #         fi
  
   Sbom:
     needs: Snyk
@@ -180,7 +180,7 @@ jobs:
     needs: [ Sbom ]
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@master
+      - uses: actions/checkout@v3
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/maven@master
         continue-on-error: true
@@ -191,7 +191,7 @@ jobs:
     needs: [ opensource-security ]
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@master
+      - uses: actions/checkout@v3
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/maven@master
         continue-on-error: true
@@ -204,7 +204,7 @@ jobs:
     needs: [ opensource-security, code-security ]
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@master
+      - uses: actions/checkout@v3
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/maven@master
         env:
