Update devsecopsworkflow.yml

diff --git a/.github/workflows/devsecopsworkflow.yml b/.github/workflows/devsecopsworkflow.yml
--- a/.github/workflows/devsecopsworkflow.yml
+++ b/.github/workflows/devsecopsworkflow.yml
@@ -35,93 +35,93 @@ jobs:
         name: coffeshopartifact
         path: ./target/*.jar
    
-  Snyk: 
-      needs: Build_and_test
-      runs-on: ubuntu-latest
-      steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  # Snyk: 
+  #     needs: Build_and_test
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
 
-      - name: Use Node.js 
-        uses: actions/setup-node@v1
-        with:
-          node-version: 11.x
-      - name: Install Snyk CLI
-        run: npm install -g snyk@1.1237.0 
+  #     - name: Use Node.js 
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: 11.x
+  #     - name: Install Snyk CLI
+  #       run: npm install -g snyk@1.1237.0 
 
-      - name: Authenticate Snyk
-        run: snyk auth ${{ secrets.SNYK_KEY }}
+  #     - name: Authenticate Snyk
+  #       run: snyk auth ${{ secrets.SNYK_KEY }}
 
-      - name: Run Snyk Test
-        run: |
-          snyk test --all-projects
-          echo $?      
-        continue-on-error: true
+  #     - name: Run Snyk Test
+  #       run: |
+  #         snyk test --all-projects
+  #         echo $?      
+  #       continue-on-error: true
         
-      - name: snyk status
-        run: |
-          echo $?
-          snyk_exit_status=$?
-          if [ $snyk_exit_status -eq 0 ]; then
-            echo "Snyk test passed, no vulnerabilities found."
-          else
-            echo "Snyk test failed, vulnerabilities found."
-            exit 1
-          fi
-  Sbom:
-    needs: Snyk
-    runs-on: ubuntu-latest
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Generate SBOM
-      run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
+  #     - name: snyk status
+  #       run: |
+  #         echo $?
+  #         snyk_exit_status=$?
+  #         if [ $snyk_exit_status -eq 0 ]; then
+  #           echo "Snyk test passed, no vulnerabilities found."
+  #         else
+  #           echo "Snyk test failed, vulnerabilities found."
+  #           exit 1
+  #         fi
+  # Sbom:
+  #   needs: Build_and_test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #   - name: Generate SBOM
+  #     run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
 
-    - name: Upload SBOM report to artifact
-      uses: actions/upload-artifact@v3
-      with:
-          name: "sbom-${{ github.run_number }}"
-          path: target/CycloneDX-Sbom.json
+  #   - name: Upload SBOM report to artifact
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #         name: "sbom-${{ github.run_number }}"
+  #         path: target/CycloneDX-Sbom.json
 
    
-  opensource-security:
-    needs: [ Sbom ]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@master
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions/maven@master
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
+  # opensource-security:
+  #   needs: [ Sbom ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Run Snyk to check for vulnerabilities
+  #       uses: snyk/actions/maven@master
+  #       continue-on-error: true
+  #       env:
+  #         SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
 
-  code-security:
-    needs: [ opensource-security ]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@master
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions/maven@master
-        continue-on-error: true
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
-        with:
-          command: code test
+  # code-security:
+  #   needs: [ opensource-security ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Run Snyk to check for vulnerabilities
+  #       uses: snyk/actions/maven@master
+  #       continue-on-error: true
+  #       env:
+  #         SNYK_TOKEN: ${{ secrets.SNYK_KEY }}
+  #       with:
+  #         command: code test
 
-  opensource-monitor:
-    needs: [ opensource-security, code-security ]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@master
-      - name: Run Snyk to check for vulnerabilities
-        uses: snyk/actions/maven@master
-        env:
-          SNYK_TOKEN: ${{ secrets.SNYK_KEY}}
-        with:
-          command: monitor
+  # opensource-monitor:
+  #   needs: [ opensource-security, code-security ]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@master
+  #     - name: Run Snyk to check for vulnerabilities
+  #       uses: snyk/actions/maven@master
+  #       env:
+  #         SNYK_TOKEN: ${{ secrets.SNYK_KEY}}
+  #       with:
+  #         command: monitor
 
   Docker_push:
-      needs: [opensource-monitor]
+      needs: [Build_and_test]
       runs-on: ubuntu-latest
   
       steps:
