Update devsecopsworkflow.yml

diff --git a/.github/workflows/devsecopsworkflow.yml b/.github/workflows/devsecopsworkflow.yml
--- a/.github/workflows/devsecopsworkflow.yml
+++ b/.github/workflows/devsecopsworkflow.yml
@@ -5,6 +5,20 @@ on:
       - dev
       - master  # Change to your default branch name if needed
 jobs:
+  GGShield:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Git_guardian
+      uses: GitGuardian/ggshield-action@v1.20.0
+      env:
+            GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
+            GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
+            GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
+            GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
+            GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
+      continue-on-error: true
   Build_and_test:
     runs-on: ubuntu-latest
     steps:
@@ -15,10 +29,42 @@ jobs:
     - name: Build Maven
       run: mvn -B package --file pom.xml
 
-    - name: Build Test Maven
-      run: mvn -B package --file pom.xml -DskipTests  
-    
+    # - name: Build Test Maven
+    #   run: mvn -B package --file pom.xml -DskipTests  
+  Snyk: 
+      runs-on: ubuntu-latest
+      steps:
+      - name: Checkout
+        uses: actions/checkout@v3
 
+      - name: Use Node.js 
+        uses: actions/setup-node@v1
+        with:
+          node-version: 11.x
+      - name: Install Snyk CLI
+        run: npm install -g snyk@1.1237.0 
+
+      - name: Authenticate Snyk
+        run: snyk auth ${{ secrets.SNYK_TOKEN }}
+
+      - name: Run Snyk Test
+        run: snyk test --all-projects
+        continue-on-error: true
+        
+      - name: Check Snyk Test Results
+        run: |
+          snyk_test_exit_code=$?
+          if [ $snyk_test_exit_code -eq 0 ]; then
+            echo "Snyk test passed, no vulnerabilities found."
+          else
+            echo "Snyk test failed, vulnerabilities found."
+            exit 1
+          fi
+  Sbom:
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
     - name: Generate SBOM
       run: mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom
 
@@ -30,7 +76,7 @@ jobs:
 
    
   opensource-security:
-    needs: [ Build_and_test ]
+    needs: [ Sbom ]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@master
@@ -82,35 +128,35 @@ jobs:
       - name: Publish Docker image
         run: docker push ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
 
-  Deploy:
-      needs: Docker_push
-      runs-on: ubuntu-latest
-      steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v3
-          with:
-            repository: danielpraveenkumar/aidevsecops   # Replace with the repository URL
-            ref: main 
-            token: ${{secrets.PAT_TOKEN }}
+  # Deploy:
+  #     needs: Docker_push
+  #     runs-on: ubuntu-latest
+  #     steps:
+  #       - name: Checkout Repository
+  #         uses: actions/checkout@v3
+  #         with:
+  #           repository: danielpraveenkumar/aidevsecops   # Replace with the repository URL
+  #           ref: main 
+  #           token: ${{secrets.PAT_TOKEN }}
 
 
   
-        - name: Modify Manifest
-          run: |
-              # Replace the image and tag in the manifest file
-              echo "GitHub Runnumber: ${{ github.run_number }}"
-              sed -i "s|${{ secrets.DOCKER_REPO }}:.*|${{ secrets.DOCKER_REPO }}:${{ github.run_number }}|" ./manifest/deployment.yaml
+  #       - name: Modify Manifest
+  #         run: |
+  #             # Replace the image and tag in the manifest file
+  #             echo "GitHub Runnumber: ${{ github.run_number }}"
+  #             sed -i "s|${{ secrets.DOCKER_REPO }}:.*|${{ secrets.DOCKER_REPO }}:${{ github.run_number }}|" ./manifest/deployment.yaml
         
-        - name: Debug - Show Git Status After Changes
-          run: git status
-          shell: bash
+  #       - name: Debug - Show Git Status After Changes
+  #         run: git status
+  #         shell: bash
   
-        - name: Commit and Push Change
-          run: |
-              git config --global user.name "DanielPraveenKumar"
-              git config --global user.email "danielpraveenkumar.k@gmail.com"
-              git add ./manifest/deployment.yaml
-              git commit -m "Update image tag"
-              git push origin main  
-          env:
-            PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
+  #       - name: Commit and Push Change
+  #         run: |
+  #             git config --global user.name "DanielPraveenKumar"
+  #             git config --global user.email "danielpraveenkumar.k@gmail.com"
+  #             git add ./manifest/deployment.yaml
+  #             git commit -m "Update image tag"
+  #             git push origin main  
+  #         env:
+  #           PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
